sudo: required
language: python
python:
  - "3.6"

install:
  - sudo apt install --yes wget
  - pip install -r requirements.txt -r requirements-devel.txt

script:
  - python3 -m unittest discover tests
