name: snappy-m-o
version: '0.2-dev'
summary: Snappy Microbe-Obliterator
description: |
  Chat ops bot for the snapcraft team.

grade: devel
confinement: classic

apps:
  snappy-m-o:
    command: env LC_ALL=C.UTF-8 PYTHONPATH=$SNAP/lib/python3.5/site-packages:$PYTHONPATH $SNAP/bin/errbot -c $SNAP/config.py

parts:
  errbot:
    source: https://github.com/errbotio/errbot/
    source-type: git
    plugin: python
    build-packages: [gcc, libffi-dev, libssl-dev]
    python-packages: [irc, gitpython, PyGithub]
  snappy-m-o:
    source: .
    plugin: dump
    stage:
      - config.py
      - plugins
  dependencies:
    plugin: nil
    stage-packages: [wget]
